server:
  port: 9001
  tomcat:
    threads:
#      tomcat最大线程数，默认为200
      max: 200
#      tomcat最大连接数
    max-connections: 300
spring:
  application:
    name: dubbo-provider
  #    解决bean重复定义。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
  main:
    allow-bean-definition-overriding: true