server:
  port: 9001
spring:
  application:
    name: dubbo-provider
  #    解决bean重复定义。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl