server:
  port: 9002
  tomcat:
    threads:
      #tomcat最大线程数，默认为200
      max: 200
    #tomcat最大连接数
    max-connections: 500
spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.93.132:8099
        port: 8179
feign:
  sentinel:
    enabled: true
#监控管理
management:
  endpoint:
    web:
      exposure:
        include: "*"